/**
 * 智能技能执行协调器
 * 负责按顺序执行技能组，每个技能执行前进行参数确认
 */

import type { Scenario, Task } from '../../types'
import { useTaskStore } from '../../stores/taskStore'
import { useScheduleStore } from '../../stores/scheduleStore'
import { useMessageStore } from '../../stores/messageStore'

interface SkillExecutionContext {
  scenario: Scenario
  scheduleId: string
  // userInput: string,
  extractedParams: Record<string, any>
}

interface SkillExecutionResult {
  success: boolean
  taskId: string
  skillCode: string
  message: string
  nextAction?: 'continue' | 'confirm' | 'complete'
  confirmMessage?: string
}

export class SmartSkillCoordinator {
  private taskStore = useTaskStore()
  private scheduleStore = useScheduleStore()
  private messageStore = useMessageStore()

  /**
   * 执行场景技能组
   */
  async executeScenarioSkills(context: SkillExecutionContext): Promise<{
    success: boolean
    executedSkills: SkillExecutionResult[]
    finalMessage: string
  }> {
    const { scenario, scheduleId, /* userInput, */ extractedParams } = context
    const executedSkills: SkillExecutionResult[] = []
    
    console.log(`[SmartCoordinator] 开始执行场景: ${scenario.name}`, {
      scheduleId,
      skillCount: scenario.skills.length
    })

    // 为每个技能创建任务
    const tasks = this.createSkillTasks(scenario, scheduleId)
    this.taskStore.addTasks(tasks)

    // 逐个执行技能
    for (const task of tasks) {
      try {
        const result = await this.executeSingleSkill(task, /* userInput, */ extractedParams)
        executedSkills.push(result)
        
        // 发送执行结果消息
        this.messageStore.addSystemMessage(result.message)
        
        // 如果需要确认，暂停执行
        if (result.nextAction === 'confirm' && result.confirmMessage) {
          this.messageStore.addSystemMessage(result.confirmMessage)
          // 这里应该触发用户确认流程
          break
        }
        
      } catch (error) {
        console.error(`[SmartCoordinator] 技能执行失败: ${task.skill}`, error)
        executedSkills.push({
          success: false,
          taskId: task.id,
          skillCode: task.skill,
          message: `❌ 技能"${task.title}"执行失败: ${(error as Error).message}`
        })
      }
    }

    const allSuccess = executedSkills.every(r => r.success)
    const finalMessage = allSuccess 
      ? `✅ ${scenario.name}场景的所有技能已成功执行`
      : `⚠️ ${scenario.name}场景部分技能执行完成`

    return {
      success: allSuccess,
      executedSkills,
      finalMessage
    }
  }

  /**
   * 创建技能任务列表
   */
  private createSkillTasks(scenario: Scenario, scheduleId: string): Task[] {
    return scenario.skills.map((skillCode, index) => ({
      id: `auto-task-${scheduleId}-${skillCode}-${Date.now()}-${index}`,
      scheduleId,
      title: this.getSkillDisplayName(skillCode),
      desc: this.getSkillDescription(skillCode),
      icon: this.getSkillIcon(skillCode),
      skill: skillCode,
      actionBtn: '执行',
      date: new Date().toISOString().split('T')[0] || new Date().toLocaleDateString('sv-SE'),
      status: 'pending' as const,
      meta: {
        autoGenerated: true,
        executionOrder: index,
        scenarioCode: scenario.code
      }
    }))
  }

  /**
   * 执行单个技能
   */
  private async executeSingleSkill(
    task: Task,
    // userInput: string,
    extractedParams: Record<string, any>
  ): Promise<SkillExecutionResult> {
    console.log(`[SmartCoordinator] 执行技能: ${task.skill}`, { taskId: task.id })
    
    try {
      // 检查是否需要参数确认
      const paramCheck = this.checkRequiredParameters(task.skill, extractedParams)
      
      if (!paramCheck.ready) {
        return {
          success: true,
          taskId: task.id,
          skillCode: task.skill,
          message: `🔍 技能"${task.title}"需要确认参数: ${paramCheck.missingParams.join(', ')}`,
          nextAction: 'confirm',
          confirmMessage: this.generateParameterConfirmation(task, paramCheck.missingParams)
        }
      }

      // 执行技能（这里应该调用实际的技能执行逻辑）
      const executionResult = await this.invokeSkill(task.skill, extractedParams)
      
      // 更新任务状态
      this.taskStore.updateTaskStatus(task.id, 'done')
      
      return {
        success: executionResult.success,
        taskId: task.id,
        skillCode: task.skill,
        message: executionResult.message
      }
      
    } catch (error) {
      this.taskStore.updateTaskStatus(task.id, 'pending')
      throw error
    }
  }

  /**
   * 检查所需参数
   */
  private checkRequiredParameters(
    skillCode: string,
    availableParams: Record<string, any>
  ): { ready: boolean; missingParams: string[] } {
    const requiredParamsMap: Record<string, string[]> = {
      'book_meeting_room': ['location', 'date', 'startTime'],
      'notify_attendees': ['attendees', 'date', 'startTime'],
      'arrange_transport': ['from', 'to', 'date'],
      'check_hotel': ['to', 'date']
    }

    const requiredParams = requiredParamsMap[skillCode] || []
    const missingParams = requiredParams.filter(param => 
      !availableParams[param] || availableParams[param] === ''
    )

    return {
      ready: missingParams.length === 0,
      missingParams
    }
  }

  /**
   * 生成参数确认消息
   */
  private generateParameterConfirmation(task: Task, missingParams: string[]): string {
    const paramNames: Record<string, string> = {
      'location': '地点',
      'date': '日期',
      'startTime': '开始时间',
      'attendees': '参会人员',
      'from': '出发地',
      'to': '目的地'
    }

    const missingNames = missingParams.map(p => paramNames[p] || p)
    
    return `请确认${task.title}的${missingNames.join('和')}信息`
  }

  /**
   * 调用技能执行
   * 通过传统 skillRegistry 执行真实技能逻辑
   */
  private async invokeSkill(
    skillCode: string,
    params: Record<string, any>
  ): Promise<{ success: boolean; message: string }> {
    try {
      // 使用传统模式的 executeSkill 执行真实技能
      const { executeSkill } = await import('../traditional/skillRegistry')
      
      // 从参数或上下文构建 schedule 对象用于技能执行
      const scheduleId = params.scheduleId || ''
      const schedule = scheduleId ? this.scheduleStore.getSchedule(scheduleId) : null
      
      if (schedule) {
        const result = await executeSkill(skillCode, schedule)
        return {
          success: true,
          message: result.text 
            ? `✅ 技能"${this.getSkillDisplayName(skillCode)}"执行成功: ${result.text}`
            : `✅ 技能"${this.getSkillDisplayName(skillCode)}"执行成功`
        }
      }
      
      // 无法找到关联日程，返回需要更多信息
      return {
        success: false,
        message: `⚠️ 技能"${this.getSkillDisplayName(skillCode)}"执行失败: 未找到关联日程`
      }
    } catch (error) {
      return {
        success: false,
        message: `❌ 技能"${this.getSkillDisplayName(skillCode)}"执行出错: ${(error as Error).message}`
      }
    }
  }

  // 辅助方法
  private getSkillDisplayName(skillCode: string): string {
    const names: Record<string, string> = {
      'book_meeting_room': '预订会议室',
      'notify_attendees': '通知参会人',
      'arrange_transport': '交通安排',
      'check_hotel': '预订酒店',
      'search_contacts': '通讯录查询',
      'apply_trip': '出差申请'
    }
    return names[skillCode] || skillCode
  }

  private getSkillDescription(skillCode: string): string {
    const descriptions: Record<string, string> = {
      'book_meeting_room': '智能预订合适的会议室',
      'notify_attendees': '向参会人员发送会议邀请',
      'arrange_transport': '规划最优出行路线',
      'check_hotel': '查找并预订合适酒店',
      'search_contacts': '查询联系人信息',
      'apply_trip': '提交出差申请流程'
    }
    return descriptions[skillCode] || ''
  }

  private getSkillIcon(skillCode: string): string {
    const icons: Record<string, string> = {
      'book_meeting_room': 'fa-door-open',
      'notify_attendees': 'fa-envelope',
      'arrange_transport': 'fa-car',
      'check_hotel': 'fa-hotel',
      'search_contacts': 'fa-address-book',
      'apply_trip': 'fa-file-contract'
    }
    return icons[skillCode] || 'fa-cube'
  }
}